### ISSUE TITLE
Storybook demo site doesn't work

### ISSUE THREAD

**Issue by gofix** [Amsterdam/amsterdam-styled-components#577]
**Describe the bug**
The storybook demosite, as advertised in your readme.md, doesn't work, it gives a 404

**To Reproduce**
1. Go to https://amsterdam.github.io/amsterdam-styled-components/
2. See error

**Expected behavior**
I'd expect a working storybook to inspect the looks and markup of the components

**Screenshots**
![image](https://user-images.githubusercontent.com/2689559/81822162-0bad5100-9533-11ea-9827-a64a1c5e7213.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version" 81

**Additional context**
I tried to clone and build the repo myself:
- git clone...
- `npm install --save @datapunt/asc-assets @datapunt/asc-ui` (as described in readme.md)
- yarn
- yarn build
- yarn start
but that also doesn't work:
```
3:59:28 PM - Starting compilation in watch mode...
[0] 
[1] ERR! Error: Your project's `baseUrl` can only be set to `src` or `node_modules`. Create React App does not support other values at this time.
[1] ERR!     at getAdditionalModulePaths (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/modules.js:59:9)
[1] ERR!     at getModules (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/modules.js:139:33)
[1] ERR!     at Object.<anonymous> (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/modules.js:149:18)
[1] ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
[1] ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1] ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
[1] ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1] ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1] ERR!     at Module.require (internal/modules/cjs/loader.js:692:17)
[1] ERR!     at require (internal/modules/cjs/helpers.js:25:18)
[1] ERR!     at Object.<anonymous> (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/webpack.config.js:30:17)
[1] ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
[1] ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1] ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
[1] ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1] ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1] ERR!  { Error: Your project's `baseUrl` can only be set to `src` or `node_modules`. Create React App does not support other values at this time.
[1] ERR!     at getAdditionalModulePaths (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/modules.js:59:9)
[1] ERR!     at getModules (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/modules.js:139:33)
[1] ERR!     at Object.<anonymous> (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/modules.js:149:18)
[1] ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
[1] ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1] ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
[1] ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1] ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1] ERR!     at Module.require (internal/modules/cjs/loader.js:692:17)
[1] ERR!     at require (internal/modules/cjs/helpers.js:25:18)
[1] ERR!     at Object.<anonymous> (/Users/gofix/Code/Packages/amsterdam-styled-components/node_modules/react-scripts/config/webpack.config.js:30:17)
[1] ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
[1] ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
[1] ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1] ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by chrisvanmook** [comment]
@gofix Het werkt weer!
